const COMPOSITION_DIRECTION_NAME = '구성 방향';
const PURPOSE_NAME = '목적';
const GOAL_NAME = '목표';
const ORGANIZATION_NAME = '편성';
const OPERATION_NAME = '운영';
const TEACHING_METHOD_NAME = '교수·학습 방법';
const EVALUATION_NAME = '평가';

const SUMMARY_NAME = {
    COMPOSITION_DIRECTION_NAME,
    PURPOSE_NAME,
    GOAL_NAME,
    ORGANIZATION_NAME,
    OPERATION_NAME,
    TEACHING_METHOD_NAME,
    EVALUATION_NAME
};

export default  SUMMARY_NAME;